
import React from 'react';
import { motion } from 'framer-motion';
import { Scale, BookOpen, Pen, AlertCircle, ChevronLeft } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-24 min-h-screen">
      <motion.button 
        initial={{ opacity: 0, x: -10 }}
        animate={{ opacity: 1, x: 0 }}
        onClick={onBack}
        className="flex items-center gap-2 text-stone-500 hover:text-stone-900 dark:text-stone-400 dark:hover:text-white mb-12 transition-colors font-bold uppercase tracking-widest text-xs"
      >
        <ChevronLeft size={16} /> Back to Studio
      </motion.button>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="prose prose-stone dark:prose-invert max-w-none"
      >
        <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-stone-900 rounded-2xl flex items-center justify-center text-white">
                <Scale size={24} />
            </div>
            <h1 className="font-serif text-5xl font-bold mb-0">Terms of Service</h1>
        </div>

        <p className="lead text-xl text-stone-500 mb-12">
          By using Novelia AI, you agree to these terms governing co-authorship and platform usage.
        </p>

        <section className="mb-12">
          <h2 className="font-serif text-3xl font-bold flex items-center gap-3">
            <BookOpen className="text-stone-400" size={24} /> 1. Co-Authorship & Ownership
          </h2>
          <p>
            You retain all rights to the <strong>creative direction, plots, and characters</strong> you conceptualize through our wizard. While the prose is generated by our neural engine, we consider the final work a collaborative effort where the user holds the proprietary interest in the final output for non-commercial and commercial purposes (subject to regional AI copyright laws).
          </p>
        </section>

        <section className="mb-12">
          <h2 className="font-serif text-3xl font-bold flex items-center gap-3">
            <Pen className="text-stone-400" size={24} /> 2. Content Guidelines
          </h2>
          <p>
            You agree not to use Novelia AI to generate content that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Violates Google's Generative AI Prohibited Use Policy.</li>
            <li>Promotes illegal activities, hate speech, or severe violence.</li>
            <li>Infringes on the intellectual property of established authors.</li>
          </ul>
        </section>

        <section className="mb-12">
          <h2 className="font-serif text-3xl font-bold flex items-center gap-3">
            <AlertCircle className="text-stone-400" size={24} /> 3. Limitation of Liability
          </h2>
          <p>
            Novelia AI is provided "as is". AI generation can be unpredictable. We do not guarantee the factual accuracy, thematic consistency, or grammatical perfection of generated text. We are not responsible for any loss of data occurring due to browser local storage failure.
          </p>
        </section>

        <footer className="pt-12 border-t border-stone-200 dark:border-stone-800 text-stone-400 text-sm italic">
          Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
        </footer>
      </motion.div>
    </div>
  );
};
